package edu.uniajc.ais.model;
// Generated Nov 7, 2017 7:42:29 PM by Hibernate Tools 5.2.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ClassParameters generated by hbm2java
 */
@Entity
@Table(name = "class_parameters")
public class ClassParameters implements java.io.Serializable {

	private int id;
	private String description;

	public ClassParameters() {
	}

	public ClassParameters(int id) {
		this.id = id;
	}

	public ClassParameters(int id, String description) {
		this.id = id;
		this.description = description;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "description", length = 50)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
